### ISSUE TITLE
Put in production the 1.0

### ISSUE THREAD

**Issue by RaitoBezarius** [jilljenn/voyageavecmoi#25]
So that it can be useful for real !

(I brace myself for this day.)

**Comment by progval** [comment]
I saw on the pad someone purchased voyageavecmoi.xyz. Is that you?
I can provide a server if you want.

**Comment by RaitoBezarius** [comment]
Yes, it is me and I have already an droplet running, ready for that.
I _may_ need an additional server for the RethinkDB instance.

**Comment by jilljenn** [comment]
I think we need to have a description page asap. I can start it, but how to guarantee updates even if one of you is sleeping? Shouldn't we just consider GitHub Pages?

**Comment by RaitoBezarius** [comment]
What do you mean by updates ?
We can setup a GitHub hook, whenever someone push to the production branch, the server pull the new version and run the deployement phase.

**Comment by jilljenn** [comment]
Okay. But when do you think voyageavecmoi.xyz can be functional, even just for serving static pages? (Awesome work, by the way.)

**Comment by RaitoBezarius** [comment]
@jilljenn : Now it is. :)
NGINX + Gunicorn.

But ! We need more text to explain the project, why, where does it come from, etc...
Let's talk about that later, the 1.0 is out.
