### ISSUE TITLE
License

### ISSUE THREAD

**Issue by progval** [jilljenn/voyageavecmoi#44]
We should agree on a license.

What about MIT?

**Comment by RaitoBezarius** [comment]
Okay for me.
@jilljenn is it okay for you?

**Comment by jilljenn** [comment]
Okay, or AGPL?

**Comment by RaitoBezarius** [comment]
AGPL seems even better for me, what about @ProgVal ?

**Comment by progval** [comment]
ok

**Comment by RaitoBezarius** [comment]
So, it has been decided!
